version: '3'

services:

  airport_rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'airport_rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  ship_management_db:
    image: 'mongo'
    container_name: 'ship_management_db'
    ports:
      - '27020:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ship_management_service:
    build: Harbor_ShipManagementService/.
    container_name: 'ship_management_service'
    ports:
      - '8091:8080'
    environment:
      - MONGO_URL=mongodb://ship_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - ship_management_db

  shipservice_management_db:
    image: 'mongo'
    container_name: 'shipservice_management_db'
    ports:
      - '27021:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  shipservice_management_service:
    build: Harbor_ShipService/.
    container_name: 'shipservice_management_service'
    ports:
      - '8092:8080'
    environment:
      - MONGO_URL=mongodb://shipservice_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipservice_management_db

  harbor_management_db:
    image: 'mongo'
    container_name: 'harbor_management_db'
    ports:
      - '27022:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  harbor_management_service:
    build: Harbor_HarborManagementService/.
    container_name: 'harbor_management_service'
    ports:
      - '8093:8080'
    environment:
      - MONGO_URL=mongodb://harbor_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipservice_management_db

  ### Dock Service ###
  dock_management_db:
    image: 'mongo'
    container_name: 'dock_management_db'
    ports:
      - '27023:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  dock_management:
    build: Harbor_DockManagement/.
    container_name: 'dock_management'
    ports:
      - '8094:8080'
    environment:
      - MONGO_URL=mongodb://dock_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - dock_management_db

  ### public Service ###
  public_service_db:
    image: 'mongo'
    container_name: 'public_service_db'
    ports:
      - '27024:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  public_service:
    build: Harbor_PublicService/.
    container_name: 'public_service'
    ports:
      - '8095:8080'
    environment:
      - MONGO_URL=mongodb://dock_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - dock_management_db

  fueling_service_db:
    image: 'mongo'
    container_name: 'fueling_service_db'
    ports:
      - '27030:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  fueling_service:
    build: Harbor_FuelingService/.
    container_name: 'fueling_service'
    ports:
      - '8098:8080'
    environment:
      - MONGO_URL=mongodb://fueling_service_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - fueling_service_db

  ### Shipping Company Service ###
  shipping_company_management_db:
    image: 'mongo'
    container_name: 'shipping_company_management_db'
    ports:
      - '27025:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  shipping_company_management:
    build: Harbor_ShippingCompanyService/.
    container_name: 'shipping_company_management'
    ports:
      - '8096:8080'
    environment:
      - MONGO_URL=mongodb://shipping_company_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipping_company_management_db
      
  ### Report Service ###
  report_service_db:
    image: 'mongo'
    container_name: 'report_service__db'
    ports:
      - '27026:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  report_service:
    build: Harbor_ReportService/.
    container_name: 'report_service'
    ports:
      - '8097:8080'
    environment:
      - MONGO_URL=mongodb://report_service_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - report_service_db
