version: '3'

services:

  airport_rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'airport_rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  ### Flight mngmnt ###
  flight_management_db:
    image: 'mongo'
    container_name: 'flight_management_db'
    restart: on-failure
    ports:
      - '27011:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  flight_management_service:
    build: FlightManagementService/.
    container_name: 'flight_management_service'
    restart: on-failure
    ports:
      - '8081:8080'
    environment:
      - MONGO_URL=mongodb://flight_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - flight_management_db

  ### Airplane mngmnt ###
  airplane_management_db:
    image: 'mongo'
    container_name: 'airplane_management_db'
    ports:
      - '27012:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  airplane_management_service:
    build: AirplaneManagementService/.
    container_name: 'airplane_management_service'
    ports:
      - '8082:8080'
    environment:
      - MONGO_URL=mongodb://airplane_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - airplane_management_db

  ship_management_db:
    image: 'mongo'
    container_name: 'ship_management_db'
    ports:
      - '27020:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  ship_management_service:
    build: Harbor_ShipManagementService/.
    container_name: 'ship_management_service'
    ports:
      - '8091:8080'
    environment:
      - MONGO_URL=mongodb://ship_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - ship_management_db

  shipservice_management_db:
    image: 'mongo'
    container_name: 'shipservice_management_db'
    ports:
      - '27021:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  shipservice_management_service:
    build: Harbor_ShipService/.
    container_name: 'shipservice_management_service'
    ports:
      - '8092:8080'
    environment:
      - MONGO_URL=mongodb://shipservice_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipservice_management_db

  harbor_management_db:
    image: 'mongo'
    container_name: 'harbor_management_db'
    ports:
      - '27022:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  harbor_management_service:
    build: Harbor_HarborManagementService/.
    container_name: 'harbor_management_service'
    ports:
      - '8093:8080'
    environment:
      - MONGO_URL=mongodb://harbor_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipservice_management_db

  ### Dock Service ###
  dock_management_db:
    image: 'mongo'
    container_name: 'dock_management_db'
    ports:
      - '27023:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  dock_management:
    build: Harbor_DockManagement/.
    container_name: 'dock_management'
    ports:
      - '8094:8080'
    environment:
      - MONGO_URL=mongodb://dock_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - dock_management_db

  ### public Service ###
  public_service_db:
    image: 'mongo'
    container_name: 'public_service_db'
    ports:
      - '27024:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  public_service:
    build: Harbor_PublicService/.
    container_name: 'public_service'
    ports:
      - '8095:8080'
    environment:
      - MONGO_URL=mongodb://dock_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - dock_management_db

  fueling_service_db:
    image: 'mongo'
    container_name: 'fueling_service_db'
    ports:
      - '27030:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  fueling_service:
    build: Harbor_FuelingService/.
    container_name: 'fueling_service'
    ports:
      - '8098:8080'
    environment:
      - MONGO_URL=mongodb://fueling_service_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - fueling_service_db

  ### Shipping Company Service ###
  shipping_company_management_db:
    image: 'mongo'
    container_name: 'shipping_company_management_db'
    ports:
      - '27025:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  shipping_company_management:
    build: Harbor_ShippingCompanyService/.
    container_name: 'shipping_company_management'
    ports:
      - '8096:8080'
    environment:
      - MONGO_URL=mongodb://shipping_company_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - shipping_company_management_db

  ### Airside mngmnt ###
  airside_db:
    image: 'mongo'
    container_name: 'airside_db'
    ports:
      - '27013:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  airside_service:
    build: AirsideService/.
    container_name: 'airside_service'
    restart: on-failure
    ports:
      - '8083:8080'
    environment:
      - MONGO_URL=mongodb://airside_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - airside_db

  ###  gate mngmnt###
  gate_management_db:
    image: 'mongo'
    container_name: 'gate_management_db'
    ports:
      - '27015:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  gate_management_service:
    build: GateManagementService/.
    container_name: 'gate_management_service'
    ports:
      - '8085:8080'
    environment:
      - MONGO_URL=mongodb://gate_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - gate_management_db

  ### employee mngmnt ###
  employee_management_db:
    image: 'mongo'
    container_name: 'employee_management_db'
    ports:
      - '27016:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  employee_management_service:
    build: EmployeeManagementService/.
    container_name: 'employee_management_service'
    ports:
      - '8086:8080'
    environment:
      - MONGO_URL=mongodb://employee_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - employee_management_db

  ### checkin mngmnt ###
  checkin_management_db:
    image: 'mongo'
    container_name: 'checkin_management_db'
    ports:
      - '27017:27017'
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
    command: ["-f", "/etc/mongod.conf"]

  checkin_management_service:
    build: CheckinManagementService/.
    container_name: 'checkin_management_service'
    ports:
      - '8087:8080'
    environment:
      - MONGO_URL=mongodb://checkin_management_db:27017/app_development
      - MQ_URL=amqp://airport_rabbitmq:5672
    depends_on:
      - airport_rabbitmq
      - checkin_management_db



      ### Harbor ###
    ### ShipManagement Service ###
